project:
  type: website

website:
  title: "Exploring Quarto: A Modern Approach to Dynamic Document Creation"
"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/doniasyriac
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



